// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package pbfiles

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProdModel struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdModel) Reset()         { *m = ProdModel{} }
func (m *ProdModel) String() string { return proto.CompactTextString(m) }
func (*ProdModel) ProtoMessage()    {}
func (*ProdModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *ProdModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdModel.Unmarshal(m, b)
}
func (m *ProdModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdModel.Marshal(b, m, deterministic)
}
func (m *ProdModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdModel.Merge(m, src)
}
func (m *ProdModel) XXX_Size() int {
	return xxx_messageInfo_ProdModel.Size(m)
}
func (m *ProdModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdModel.DiscardUnknown(m)
}

var xxx_messageInfo_ProdModel proto.InternalMessageInfo

func (m *ProdModel) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProdModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ProdRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdRequest) Reset()         { *m = ProdRequest{} }
func (m *ProdRequest) String() string { return proto.CompactTextString(m) }
func (*ProdRequest) ProtoMessage()    {}
func (*ProdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *ProdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdRequest.Unmarshal(m, b)
}
func (m *ProdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdRequest.Marshal(b, m, deterministic)
}
func (m *ProdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdRequest.Merge(m, src)
}
func (m *ProdRequest) XXX_Size() int {
	return xxx_messageInfo_ProdRequest.Size(m)
}
func (m *ProdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProdRequest proto.InternalMessageInfo

func (m *ProdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ProdResponse struct {
	Result               *ProdModel `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProdResponse) Reset()         { *m = ProdResponse{} }
func (m *ProdResponse) String() string { return proto.CompactTextString(m) }
func (*ProdResponse) ProtoMessage()    {}
func (*ProdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{2}
}

func (m *ProdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdResponse.Unmarshal(m, b)
}
func (m *ProdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdResponse.Marshal(b, m, deterministic)
}
func (m *ProdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdResponse.Merge(m, src)
}
func (m *ProdResponse) XXX_Size() int {
	return xxx_messageInfo_ProdResponse.Size(m)
}
func (m *ProdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProdResponse proto.InternalMessageInfo

func (m *ProdResponse) GetResult() *ProdModel {
	if m != nil {
		return m.Result
	}
	return nil
}

type UserInfo struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserScore            int32    `protobuf:"varint,2,opt,name=user_score,json=userScore,proto3" json:"user_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetUserScore() int32 {
	if m != nil {
		return m.UserScore
	}
	return 0
}

type UserScoreRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserScoreRequest) Reset()         { *m = UserScoreRequest{} }
func (m *UserScoreRequest) String() string { return proto.CompactTextString(m) }
func (*UserScoreRequest) ProtoMessage()    {}
func (*UserScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{4}
}

func (m *UserScoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserScoreRequest.Unmarshal(m, b)
}
func (m *UserScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserScoreRequest.Marshal(b, m, deterministic)
}
func (m *UserScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserScoreRequest.Merge(m, src)
}
func (m *UserScoreRequest) XXX_Size() int {
	return xxx_messageInfo_UserScoreRequest.Size(m)
}
func (m *UserScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserScoreRequest proto.InternalMessageInfo

func (m *UserScoreRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserScoreResponse struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserScoreResponse) Reset()         { *m = UserScoreResponse{} }
func (m *UserScoreResponse) String() string { return proto.CompactTextString(m) }
func (*UserScoreResponse) ProtoMessage()    {}
func (*UserScoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{5}
}

func (m *UserScoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserScoreResponse.Unmarshal(m, b)
}
func (m *UserScoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserScoreResponse.Marshal(b, m, deterministic)
}
func (m *UserScoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserScoreResponse.Merge(m, src)
}
func (m *UserScoreResponse) XXX_Size() int {
	return xxx_messageInfo_UserScoreResponse.Size(m)
}
func (m *UserScoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserScoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserScoreResponse proto.InternalMessageInfo

func (m *UserScoreResponse) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*ProdModel)(nil), "ProdModel")
	proto.RegisterType((*ProdRequest)(nil), "ProdRequest")
	proto.RegisterType((*ProdResponse)(nil), "ProdResponse")
	proto.RegisterType((*UserInfo)(nil), "UserInfo")
	proto.RegisterType((*UserScoreRequest)(nil), "UserScoreRequest")
	proto.RegisterType((*UserScoreResponse)(nil), "UserScoreResponse")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573) }

var fileDescriptor_0b5431a010549573 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0x6c, 0x62, 0x33, 0x2d, 0x5a, 0x17, 0x24, 0x25, 0x20, 0x86, 0x3d, 0x48, 0x41,
	0x4c, 0xa0, 0x1e, 0xbd, 0xe5, 0xd6, 0x83, 0x20, 0x2b, 0xbd, 0x78, 0x91, 0x34, 0x3b, 0x91, 0x40,
	0x92, 0x8d, 0x3b, 0x89, 0x9f, 0xd1, 0xcf, 0xd4, 0x93, 0x6c, 0xfe, 0x54, 0x2f, 0xde, 0xde, 0xcc,
	0x7b, 0x6f, 0xf6, 0xc7, 0xc2, 0xb2, 0x52, 0x12, 0x4b, 0x8a, 0x1a, 0xad, 0x5a, 0x15, 0xf8, 0x5f,
	0x69, 0x59, 0xc8, 0xb4, 0xc5, 0x78, 0x12, 0x83, 0xc1, 0x63, 0xf0, 0x5e, 0xb4, 0x92, 0xcf, 0x26,
	0xcc, 0x2e, 0xc0, 0x2e, 0xe4, 0xda, 0x0a, 0xad, 0x8d, 0x23, 0xec, 0x42, 0x32, 0x06, 0xb3, 0x3a,
	0xad, 0x70, 0x6d, 0x87, 0xd6, 0xc6, 0x13, 0xbd, 0xe6, 0x11, 0x2c, 0x4c, 0x41, 0xe0, 0x67, 0x87,
	0xd4, 0xb2, 0xdb, 0xdf, 0x4a, 0x72, 0x79, 0x4c, 0x66, 0x81, 0x1d, 0xca, 0x63, 0xe2, 0x04, 0x67,
	0xab, 0x6f, 0xcb, 0xdc, 0xe0, 0x5b, 0x58, 0x0e, 0x79, 0x6a, 0x54, 0x4d, 0xc8, 0x38, 0xb8, 0x1a,
	0xa9, 0x2b, 0xdb, 0xbe, 0xb4, 0xd8, 0x42, 0x74, 0x7a, 0x5f, 0x8c, 0x0e, 0x4f, 0x60, 0xbe, 0x27,
	0xd4, 0xbb, 0x3a, 0x57, 0xcc, 0x87, 0xf3, 0x8e, 0x50, 0xbf, 0x9f, 0xc0, 0x5c, 0x33, 0xee, 0x24,
	0xbb, 0x01, 0xe8, 0x0d, 0xca, 0x94, 0x1e, 0x10, 0x1d, 0xe1, 0x99, 0xcd, 0xab, 0x59, 0xf0, 0x7b,
	0x58, 0xed, 0xa7, 0x61, 0x82, 0xfd, 0xef, 0x16, 0x7f, 0x82, 0xab, 0x3f, 0xe1, 0x91, 0xf4, 0x0e,
	0xbc, 0x21, 0x5d, 0xe7, 0x6a, 0x84, 0xf5, 0xa2, 0x89, 0x4b, 0xcc, 0xbb, 0x51, 0x25, 0xfe, 0xdb,
	0xf5, 0x87, 0x6e, 0xb2, 0x07, 0x89, 0x95, 0x8a, 0x49, 0x67, 0x71, 0x73, 0xc8, 0x8b, 0x12, 0xe9,
	0xe0, 0xf6, 0x5f, 0xfc, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0x06, 0xcf, 0x17, 0xea, 0x8b, 0x01,
	0x00, 0x00,
}
