// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: models.proto

package pbfiles

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ProdModel with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *ProdModel) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Name

	return nil
}

// ProdModelValidationError is the validation error returned by
// ProdModel.Validate if the designated constraints aren't met.
type ProdModelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProdModelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProdModelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProdModelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProdModelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProdModelValidationError) ErrorName() string { return "ProdModelValidationError" }

// Error satisfies the builtin error interface
func (e ProdModelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProdModel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProdModelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProdModelValidationError{}

// Validate checks the field values on ProdRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ProdRequest) Validate() error {
	if m == nil {
		return nil
	}

	if val := m.GetId(); val <= 100 || val >= 200 {
		return ProdRequestValidationError{
			field:  "Id",
			reason: "value must be inside range (100, 200)",
		}
	}

	return nil
}

// ProdRequestValidationError is the validation error returned by
// ProdRequest.Validate if the designated constraints aren't met.
type ProdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProdRequestValidationError) ErrorName() string { return "ProdRequestValidationError" }

// Error satisfies the builtin error interface
func (e ProdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProdRequestValidationError{}

// Validate checks the field values on ProdResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ProdResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProdResponseValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ProdResponseValidationError is the validation error returned by
// ProdResponse.Validate if the designated constraints aren't met.
type ProdResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProdResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProdResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProdResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProdResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProdResponseValidationError) ErrorName() string { return "ProdResponseValidationError" }

// Error satisfies the builtin error interface
func (e ProdResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProdResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProdResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProdResponseValidationError{}
